const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
process.chdir(path.join(__dirname, '..'));
const elements = new Map();
function el(id) { if (!elements.has(id)) elements.set(id, { id, textContent:'', innerHTML:'', value:'', hidden:false, dataset:{}, style:{setProperty(){}}, classList:{toggle(){},add(){},remove(){}}, setAttribute(){}, removeAttribute(){}, addEventListener(){}, querySelector(){return el(id+'child');}, querySelectorAll(){return [];} }); return elements.get(id); }
const storage = new Map();
const ctx = {window:{},document:{getElementById:el,querySelector:el,querySelectorAll:()=>[],addEventListener(){}},navigator:{onLine:false},location:{search:'?lake=lembolovo'},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},URLSearchParams,URL,Date,console,setTimeout,clearTimeout,AbortSignal};
vm.createContext(ctx);
for (const file of ['data.js','trip-data.js']) vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
const source = fs.readFileSync('app.js','utf8').replace('  document.addEventListener("DOMContentLoaded", boot);', '  window.test = {scoreAt,conditionsAt,weatherUsable,bestWindows,rankedHotspots,pointInWater,estimateDepth,moscowDay,moscowHour,renderAll,weatherUrl,renderExpedition, inject(data,at){weather=data;weatherCache[selectedLake]={data,at};},select(key){selectedLake=key;}};');
vm.runInContext(source,ctx);
const t=ctx.window.test, lake=ctx.window.LAKE_DATA.lembolovo;
assert.equal(Object.keys(ctx.window.LAKE_DATA).length,4);
assert.equal(t.scoreAt(new Date()),null);
assert.equal(t.bestWindows().length,0);
assert.equal(t.estimateDepth(...lake.center),null);
assert.match(t.weatherUrl(),/latitude=60.391/);
assert.match(t.weatherUrl(),/wind_speed_unit=ms/);
for (const spot of lake.hotspots) assert(t.pointInWater([spot.lat,spot.lon]),spot.id+' must be in water');
assert(!t.pointInWater([lake.expedition.access[0].lat,lake.expedition.access[0].lon]),'access must be on land');
const island=lake.holes[0].slice(0,-1).reduce((a,p)=>[a[0]+p[0]/3,a[1]+p[1]/3],[0,0]);
assert(!t.pointInWater(island),'island is not water');
assert.equal(t.rankedHotspots('pike').length,3);
assert.equal(t.rankedHotspots('roach').length,2);
assert.equal(t.rankedHotspots('bream').length,1);
assert.equal(t.moscowHour(new Date('2026-09-14T23:00:00Z')),2);
assert.equal(t.moscowDay(new Date('2026-09-14T23:00:00Z')),'2026-09-15');
const start=Math.floor(Date.now()/3600000)*3600000-6*3600000;
const times=Array.from({length:54},(_,i)=>new Date(start+i*3600000+10800000).toISOString().slice(0,16));
const arr=v=>times.map(()=>v);
const data={hourly:{time:times,temperature_2m:arr(15),wind_speed_10m:arr(3),wind_gusts_10m:arr(5),wind_direction_10m:arr(90),pressure_msl:arr(1015),cloud_cover:arr(50),precipitation_probability:arr(10),weather_code:arr(2)},hourly_units:{wind_speed_10m:'m/s'},daily:{time:[...new Set(times.map(s=>s.slice(0,10)))]}};
data.daily.sunrise=data.daily.time.map(d=>d+'T06:25');data.daily.sunset=data.daily.time.map(d=>d+'T19:20');
t.inject(data,Date.now());
assert(Number.isFinite(t.scoreAt(new Date())));
assert(t.bestWindows().length>0);
assert.equal(t.scoreAt(new Date(start+80*3600000)),null);
data.hourly.wind_speed_10m.fill(null);assert.equal(t.scoreAt(new Date()),null);
data.hourly.wind_speed_10m.fill(3);data.hourly.wind_gusts_10m.fill(16);assert.equal(t.scoreAt(new Date()),8);
t.inject(data,Date.now()-7*3600000);assert.equal(t.scoreAt(new Date()),null);
assert.equal(t.bestWindows().length,0);
t.renderAll();
assert.equal(el('scoreValue').textContent,'—');
assert(!/null|NaN|undefined/.test(el('expeditionSection').innerHTML));
assert.match(el('expeditionSection').innerHTML,/Лемболовского/);
assert.match(el('fishGuide').innerHTML,/незацепляйка/);
assert(!/null|NaN|undefined/.test(el('compareList').innerHTML));
for (const key of ['krivoe','ulovnoe','sukhodol','lembolovo']) { t.select(key); t.renderAll(); }
const html=fs.readFileSync('index.html','utf8');
assert(html.indexOf('src="data.js')<html.indexOf('src="trip-data.js'));
assert(html.indexOf('src="trip-data.js')<html.indexOf('src="app.js'));
assert(fs.readFileSync('sw.js','utf8').includes('./trip-data.js'));
console.log('PASS: four lakes; species filtering; water/island/access geometry; no fake depth; weather units/freshness/nulls; Moscow time; storm guard; offline rendering; script order.');
